BASE = """<!doctype html><html lang=zh-CN><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>{{ title }} · CampusToday</title><style>
.account-tab{background:white;border:1px solid #dfe6f0;border-radius:12px;padding:15px;box-shadow:0 3px 12px #1e293b0a}.account-tab.selected{border:2px solid #2257d7;padding:14px;background:#f5f8ff}
:root{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}.nav{display:flex;gap:18px;align-items:center;background:#172033;color:white;padding:14px 24px}.nav a{color:white;text-decoration:none}.nav b{margin-right:auto}.card{background:white;border:1px solid #dfe6f0;border-radius:14px;padding:22px;margin:18px 0;box-shadow:0 4px 18px #1e293b0d}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:18px}.two-col .card{margin:0}.metric{background:white;border:1px solid #e5eaf1;padding:16px;border-radius:12px}.metric .value{display:block;font-size:25px;margin-top:7px}.muted{color:#667085}.ok{color:#137333}.warn{color:#b54708}.neutral{color:#475467}.badge{display:inline-flex;align-items:center;padding:4px 9px;border-radius:999px;background:#eef2f7;font-size:12px;font-weight:650}.badge.ok{background:#e8f5ec}.badge.warn{background:#fff1e6}.badge.neutral{background:#eef2f7}.section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:12px}.section-head h2{margin:0}.section-head p{margin:4px 0 0}.details{display:grid;grid-template-columns:145px 1fr;gap:10px 18px}.details div:nth-child(odd){color:#667085}.empty{padding:24px;text-align:center;color:#667085;background:#f8fafc;border-radius:10px}.callout{background:#fff7e8;border:1px solid #f4d8a7;border-radius:10px;padding:12px;color:#8a4b08}.mono{font-variant-numeric:tabular-nums;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}label{display:block;margin:12px 0 5px}input,select,textarea{width:100%;padding:10px;border:1px solid #c9d2df;border-radius:8px;font:inherit}textarea{min-height:86px;resize:vertical}button{background:#2257d7;color:white;border:0;border-radius:8px;padding:10px 16px;margin-top:16px;cursor:pointer}.button-secondary{background:#475467}.button-danger{background:#b42318}.actions{display:flex;gap:9px;flex-wrap:wrap}.actions form{margin:0}.actions button{margin-top:0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #e6ebf2;font-size:14px}th{color:#667085;font-weight:600}.table-wrap{overflow-x:auto}.flash{background:#fff4ce;padding:12px;border-radius:8px}@media(max-width:760px){.wrap{padding:16px}.nav{padding:12px 14px;gap:12px;overflow-x:auto}.nav b{min-width:max-content}.two-col{grid-template-columns:1fr}.details{grid-template-columns:1fr;gap:3px}.details div:nth-child(even){margin-bottom:9px}.card{padding:17px}}</style></head><body>
{% if session.get('user') %}<nav class=nav><b>CampusToday</b><a href='/dashboard'>状态</a><a href='/accounts'>账号</a><a href='/history'>历史</a><a href='/settings'>设置</a><a href='/logs'>日志</a><form action='/logout' method=post><input type=hidden name=csrf value='{{ csrf_token() }}'><button style='margin:0;background:#475467'>退出</button></form></nav>{% endif %}<main class=wrap>{% with ms=get_flashed_messages() %}{% for m in ms %}<p class=flash>{{m}}</p>{% endfor %}{% endwith %}{{ content|safe }}</main></body></html>"""

LOGIN = """<div class=card style='max-width:420px;margin:10vh auto'><h1>CampusToday</h1><p class=muted>晚查寝自动化服务管理后台</p><form method=post><input type=hidden name=csrf value='{{ csrf_token() }}'><label>用户名</label><input name=username autocomplete=username required><label>密码</label><input type=password name=password autocomplete=current-password required><button>登录</button></form></div>"""

DASHBOARD = """<div class=section-head><div><h1 style='margin-bottom:4px'>{{dashboard.selected_account.label if dashboard.selected_account else '签到状态'}}</h1><p class=muted>单账号签到状态、任务、历史与设备位置</p></div><a href=/accounts>管理账号</a></div>
<div class=grid style='margin-bottom:18px'>{% for account in dashboard.accounts %}<a href='/dashboard?account={{account.id}}' class='account-tab {{"selected" if account.selected}}' style='text-decoration:none;color:inherit'><div style='display:flex;justify-content:space-between;gap:8px'><b>{{account.label}}</b><span class='badge {{"ok" if account.session_valid else "warn"}}'>{{'有效' if account.session_valid else '失效'}}</span></div><div class=muted style='margin-top:7px'>自动签到 {{'ON' if account.auto_enabled else 'OFF'}}</div></a>{% else %}<a href=/accounts class=account-tab style='text-decoration:none;color:inherit'><b>+添加签到账号</b></a>{% endfor %}</div>
{% if dashboard.selected_account %}<div class=card style='margin-top:0'><div class=section-head style='margin:0'><div><b>{{dashboard.selected_account.label}}</b><div class=muted style='margin-top:5px'>{{dashboard.selected_account.school}} · {{dashboard.selected_account.device}}</div></div><div class=actions><form method=post action='/accounts/{{dashboard.selected_account.id}}/check' onsubmit='this.querySelector("button").disabled=true;this.querySelector("button").textContent="检测中…"'><input type=hidden name=csrf value='{{csrf_token()}}'><input type=hidden name=next value=dashboard><button class=button-secondary>刷新并检测会话</button></form><form method=post action='/accounts/{{dashboard.selected_account.id}}/toggle'><input type=hidden name=csrf value='{{csrf_token()}}'><input type=hidden name=enabled value='{{"false" if dashboard.selected_account.auto_enabled else "true"}}'><button class='{{"button-danger" if dashboard.selected_account.auto_enabled else ""}}'>{{'关闭自动签到' if dashboard.selected_account.auto_enabled else '开启自动签到'}}</button></form></div></div></div>{% endif %}
<div class=grid><div class=metric><div class=muted>今日待签任务</div><b class=value>{{dashboard.upcoming|length}}</b></div><div class=metric><div class=muted>{{dashboard.history_month}} 学校已签</div><b class=value>{{dashboard.school_signed_count}}</b></div><div class=metric><div class=muted>该账号自动签到成功</div><b class='value ok'>{{dashboard.automatic_successes}}</b></div><div class=metric><div class=muted>最近位置</div><b class='value {{"ok" if dashboard.location and dashboard.location.fresh else "warn"}}' style='font-size:18px'>{{'新鲜可用' if dashboard.location and dashboard.location.fresh else ('已过期' if dashboard.location else '尚未上传')}}</b></div></div>
{% if dashboard.school_error %}<p class=callout>当前账号的学校接口无法读取：{{dashboard.school_error}}</p>{% endif %}
<div class=two-col><section class=card><div class=section-head><div><h2>今日及即将开始</h2><p class=muted>当前账号的学校签到任务</p></div></div>{% for task in dashboard.upcoming %}<div style='padding:13px 0;border-top:1px solid #edf0f5'><div style='display:flex;justify-content:space-between;gap:8px'><b>{{task.name}}</b><span class='badge {{task.tone}}'>{{task.state}}</span></div><div class='muted mono' style='margin-top:7px'>{{task.start}} — {{task.end}}</div></div>{% else %}<div class=empty>当前账号今日暂无待签任务</div>{% endfor %}</section>
<section class=card><div class=section-head><div><h2>最近设备位置</h2><p class=muted>所有账号共用的实时位置</p></div>{% if dashboard.location %}<span class='badge {{"ok" if dashboard.location.verified else "warn"}}'>{{'验证通过' if dashboard.location.verified else '验证未通过'}}</span>{% endif %}</div>{% if dashboard.location %}<div class=details><div>坐标</div><div class=mono>{{dashboard.location.latitude}}, {{dashboard.location.longitude}} ({{dashboard.location.coordinate_system|upper}})</div><div>精度</div><div>{{dashboard.location.accuracy}} 米</div><div>定位时间</div><div>{{dashboard.location.observed_display}} <span class=muted>（{{dashboard.location.age_seconds}}秒前）</span></div><div>收到时间</div><div>{{dashboard.location.received_display}}</div><div>地址</div><div>{{dashboard.location.address or '设备未提供'}}</div><div>验证结果</div><div class={{'ok' if dashboard.location.verified else 'warn'}}>{{dashboard.location.reason}}</div></div>{% else %}<div class=empty>尚未收到设备位置</div>{% endif %}</section></div>
<section class=card><div class=section-head><div><h2>{{dashboard.history_month}} 签到记录</h2><p class=muted>当前账号的学校记录；由本服务完成的会标记“自动签到”</p></div></div><div class=table-wrap><table><thead><tr><th>日期</th><th>任务</th><th>状态</th><th>签到方式</th><th>签到/任务时间</th><th>发布人</th></tr></thead><tbody>{% for item in dashboard.school_history %}<tr><td class=mono>{{item.date}}</td><td>{{item.name}}</td><td><span class='badge {{item.tone}}'>{{item.status}}</span></td><td>{% if item.automatic %}<span class='badge ok'>自动签到</span>{% else %}<span class=muted>手动/学校状态</span>{% endif %}</td><td class=mono>{{item.time}}</td><td>{{item.publisher}}</td></tr>{% else %}<tr><td colspan=6 class=muted>当前账号本月暂无签到记录</td></tr>{% endfor %}</tbody></table></div></section>"""

ACCOUNTS = """<div class=section-head><div><h1 style='margin-bottom:4px'>签到账号</h1><p class=muted>Cookie 只保存在服务器，不会在页面回显或写入日志</p></div><span class=badge>{{accounts|length}} 个账号</span></div>
<section class=card><h2>添加账号</h2><form method=post action=/accounts><input type=hidden name=csrf value='{{csrf_token()}}'><input type=hidden name=auto_enabled value=true><label>账号名称</label><input name=name maxlength=80 placeholder='例如：张三' required><label>登录 Cookie 值</label><textarea name=session_cookie autocomplete=off spellcheck=false placeholder='直接粘贴 ST- 开头的值，系统会自动补全 Cookie 名称' required></textarea><button>添加并检测会话</button></form></section>
{% for account in accounts %}<section class=card><div class=section-head><div><h2>{{account.name}}</h2><p class=muted>最后检测：{{account.last_checked_at or '尚未检测'}}{% if account.last_error %} · {{account.last_error}}{% endif %}</p></div><span class='badge {{ "ok" if account.session_status == "VALID" else ("warn" if account.session_status == "INVALID" else "neutral") }}'>{{'会话有效' if account.session_status == 'VALID' else ('会话失效' if account.session_status == 'INVALID' else '未检测')}}</span></div>
<form method=post action='/accounts/{{account.id}}/update'><input type=hidden name=csrf value='{{csrf_token()}}'><input type=hidden name=auto_enabled value='{{"true" if account.auto_enabled else "false"}}'><label>账号名称</label><input name=name maxlength=80 value='{{account.name}}' required><label>更换 Cookie 值</label><textarea name=session_cookie autocomplete=off spellcheck=false placeholder='直接粘贴新的 ST- 值；留空表示保持不变'></textarea><button>保存修改</button></form>
<div class=actions style='margin-top:14px'><a href='/dashboard?account={{account.id}}'>查看该账号状态</a><form method=post action='/accounts/{{account.id}}/delete' onsubmit='return confirm("确定删除这个签到账号？历史执行记录会保留。")'><input type=hidden name=csrf value='{{csrf_token()}}'><button class=button-danger>删除账号</button></form></div></section>{% else %}<div class=empty>尚未添加签到账号</div>{% endfor %}"""

SETTINGS = """<h1>设置</h1><div class=card><form method=post><input type=hidden name=csrf value='{{ csrf_token() }}'><label>自动运行</label><select name=auto_enabled><option value=false {{'selected' if not status.enabled}}>OFF</option><option value=true {{'selected' if status.enabled}}>ON</option></select><label>监测开始</label><input type=time name=monitor_start value='{{values.monitor_start}}' required><label>监测结束</label><input type=time name=monitor_end value='{{values.monitor_end}}' required><button>保存</button></form></div><div class=card><h2>受保护配置</h2><p class=muted>今日校园账号、接口入口、校园围栏和可信设备令牌只能通过服务器端 <code>.env</code> 配置，避免浏览器页面泄露敏感信息。</p></div>"""

TABLE = """<h1>{{heading}}</h1><div class=card><table><thead><tr>{% for h in headers %}<th>{{h}}</th>{% endfor %}</tr></thead><tbody>{% for row in rows %}<tr>{% for cell in row %}<td>{{cell}}</td>{% endfor %}</tr>{% else %}<tr><td colspan={{headers|length}} class=muted>暂无记录</td></tr>{% endfor %}</tbody></table></div>"""
